query (
              $start:Int
              $id:ID!
              $art:Int
            ){
              lawtexts(sort: "art:asc, org:asc", start: $start, limit: 100, where: {law:{id:$id}, art:$art, questions_gt: 0}) {
                id
                art
                text
                show
                org
                structura
                revogado
                questions{
                  id
                  textQuestion
                  response
                  question_info{
                    institute
                    office
                    year
                    organizadora{
                      name
                    }
                    area
                  }
                }
                comments{
                  id
                  comments
                  type
                  tags{
                    name
                  }
                }
              },
            }