mutation(
  $id:ID!
  $response:Boolean!
  $textQuestion:String!
  $question_info:ID!
){
  createQuestion(
    input:{
      data:{
     			response:$response
          lawtext:$id
        	textQuestion:$textQuestion
      		question_info:$question_info
      }
    }
  ){
     question{
      id
    	textQuestion
      response
    }
  }
}