mutation($idUser:ID!, $favoritesLaw:[ID!]){
  updateUser(
    input:{
      where:{id:$idUser}
      data:{
        favoritesText:$favoritesLaw
      }
    }
  ){
    user{
      id
      username
      favoritesText{
      	id
        text
    }
    }
  }
}