mutation($idUser:ID!, $favoritesLaw:[ID!]){
  updateUser(
    input:{
      where:{id:$idUser}
      data:{
        favoritesLaw:$favoritesLaw
      }
    }
  ){
    user{
      id
      username
      favoritesLaw{
      	id
        law
    }
    }
  }
}